[General]
UITheme=theme-night
appdata="@ByteArray(eyJ1c2VybmFtZSI6IklubWVtb3JpYWxha2UiLCJkb2NvcGVubW9kZSI6ImVkaXQiLCJyZXN0YXJ0IjpmYWxzZSwibGFuZ2lkIjoiZXMtRVMiLCJ1aXNjYWxpbmciOiIwIiwidWl0aGVtZSI6InRoZW1lLW5pZ2h0IiwiZWRpdG9yd2luZG93bW9kZSI6ZmFsc2UsInNwZWxsY2hlY2tkZXRlY3QiOiJhdXRvIiwidXNlZ3B1IjpmYWxzZX0=)"
editorWindowMode=false
maximized=true
openPath=/home/Inmemorialake/Downloads
position=@Rect(59 32 1800 1048)
titlebar=custom
